Updated livesite with new background, logo, buttons, and new colors
Hack-PSU/frontend pull request #424
Opened 2022-11-04 06:15 UTC by jaytran505

This is an initial update to the live site. It now includes the new background, logo, and some new buttons. Kalp and I also changed the background color and the text box colors. We also switched out the wild west font and got rid of the dusty and cactus stuff. These are just the first colors we randomly chose so we can change them if we want. some screenshots below:

![image](https://user-images.githubusercontent.com/70663263/199904350-e4d81435-6dc4-4587-88e6-a832f6717342.png)
![image](https://user-images.githubusercontent.com/70663263/199904383-89ce2578-e54d-4e7a-b29e-c03aa948602e.png)
![image](https://user-images.githubusercontent.com/70663263/199904414-6d853829-e9eb-4cdf-ad7c-bca9c1d0fadc.png)

2022-11-04 07:39 UTC, susanto-tm commented
The workshops and FAQ can probably have some similar styles to the dialog box for the hero section just with a less fancy font. 

The rich text shouldn't have indents at the beginning since it's just a p tag with no inline styles.

2022-11-04 21:16 UTC, susanto-tm requested changes
Remove this line to remove the rich text padding: https://github.com/Hack-PSU/frontend/blob/fbd02c56c591aec2e3ca55fdbc316faad8409a0d/user-registration-app/src/app/views/live-workshop/live-workshop.component.html#L16

2022-11-04 21:16 UTC, susanto-tm commented on user-registration-app/src/app/views/live-view/live-view.component.css
> +  background-image: url('../../../assets/images/vapor-backgound.png');
Add `background-position: center`

2022-11-04 21:16 UTC, susanto-tm commented on user-registration-app/src/app/views/live-view/live-view.component.html
> +        <div class="col-6" style="padding-left: 10%">
remove `padding-left`

2022-11-04 23:18 UTC, susanto-tm commented
Also make the anchor links of the navbar have smooth scrolling

2022-11-05 04:52 UTC, merged

2022-11-05 04:52 UTC, jdurrell commented
Poggers, guys. Merging this